### ISSUE TITLE
Arrays as defaults in variables

### ISSUE THREAD

**Issue by spitlo** [davdebcom/post-snippets#19]
It would be great if it was possible to use an array as default value, which would then be turned into a select box in the Post Snippets popup.

So that this code in the variables field in the admin:
somevariable=['One', 'Two', 'Three']
would give the post author the possibility to chose only one of those three values.

Also, following the same logic, variables with values of true or false could be turned into a checkbox.

**Comment by davdebcom** [comment]
Not enough requests at the moment.
