### ISSUE TITLE
Shortcode should encapsulate selected text

### ISSUE THREAD

**Issue by spitlo** [davdebcom/post-snippets#20]
If you chose to have your snippet added as a shortcode, I think the average user would presume that selecting text, images or anything else before pressing the Post Snippet button would encapsulate the selected text or images in an [opening] and [/closing] shortcode tag, rather than overwrite it with only the opening tag.

**Comment by davdebcom** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 20: Shortcode should encapsulate selected text](https://trello.com/c/VFPm8A8i/24-issue-20-shortcode-should-encapsulate-selected-text)

**Comment by davdebcom** [comment]
@sultann Can you check if this works in a stable way, with backwards compatibility for the existing ays of inserting a snippet?

**Comment by davdebcom** [comment]
Discussed this with @sultann. closing for now until we get a lot more demand and/or as part of a bigger refactor. It's not requested that often compared to many other features, and the question of how we should implement this (per WordPress editor) also plays a roll.
