### ISSUE TITLE
Can't use single tick apostrophe in PHP snippet

### ISSUE THREAD

**Issue by mrjustin** [davdebcom/post-snippets#28]
I have a PHP/shortcode snippet and when I try to write, for example `[snippet variable="I can't do this"]` the single 'tick' apostrophe in "can't" causes:

`Parse error: syntax error, unexpected T_STRING in .../.../post-snippets/lib/PostSnippets/Shortcode.php(98) : eval()'d code on line 2"`

This makes sense, because it's closing my `echo`'d snippet in the PHP, but it'd be great if the plugin allowed us to write single 'tick' apostrophes instead of having to use the proper (though harder to type) typographer’s single closing apostrophe.

Thanks! (And love the plugin!)

**Comment by davdebcom** [comment]
@sultann Please review and see if we can fix it.

**Comment by sultann** [comment]
This problem has been resolved from the version v3.0.0
