### ISSUE TITLE
Move data storage from option to a table

### ISSUE THREAD

**Issue by artstorm** [davdebcom/post-snippets#30]
Extract from support email:

However, because the data is stored in options (i think this is why, anyway) when you get to a certain numbre of snippets, it ends up not allowing changes, deletions, saves, etc...

...I have a lot of snippets (150+)....

...Is there anyway you can update this to make it write to a dbase table instead so it doesn't have these limitations?

**Comment by davdebcom** [comment]
Migration to CPT or custom tables planned for 3.2 or 3.3
