### ISSUE TITLE
breaks with javascript regex in shortcode

### ISSUE THREAD

**Issue by rickdog** [davdebcom/post-snippets#32]
text is stripped from inside regular expression literals in javascript shortcodes, example:

```
<script>
var data = "";
data = data.replace(/<script[\w\W]*?>[\w\W]*?<\/script>/ig, '').replace(/<script[\w\W]*?\/>/ig, '').replace(/<noscript>([\w\W]*?)<\/noscript>/ig, "$1");
alert("OK");
</script>
```

will erroneouslly insert the following into a post/page body:

/ig, '').replace(//ig, '').replace(//ig, "$1"); alert("OK"); 

</code></pre>

**Comment by davdebcom** [comment]
@sultann Can we fix this or is it too complicated?

**Comment by sultann** [comment]
This works fine with the recent version
