### ISSUE TITLE
Store snippets as Custom Post Types

### ISSUE THREAD

**Issue by artstorm** [davdebcom/post-snippets#35]
Currently the snippets are stored as a serialized array. That has the impact that when save/update snippets, if there are too many, the max items allowed for POST in php settings might be reached. The user can then increase the PHP max allowed setting, if the user has access to do so. Not a good solution. 

By moving to Custom Post Types, we can a) list and categorize snippets in more ways out of the box. b) not be affected by any php setting limits.

**Comment by davdebcom** [comment]
Migration to CPT or custom tables planned for 3.2 or 3.3
