### ISSUE TITLE
Support PHP opening and close tags

### ISSUE THREAD

**Issue by artstorm** [davdebcom/post-snippets#36]
https://wordpress.org/support/topic/avoid-parse-errors-when-using-php-tags-or-inline-html

Support php open and close tags, to allow mix HTML and PHP code in a snippet.

**Comment by davdebcom** [comment]
@sultann Can you check if this is possible without braking backwards compatibility for exiting snippets and without the implementation taking more than half a day?

**Comment by davdebcom** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 36: Support PHP opening and close tags](https://trello.com/c/n92eNkT0/23-issue-36-support-php-opening-and-close-tags)

**Comment by davdebcom** [comment]
@sultann and I discussed this and there seems to be no way to ensure backwards compatibility. So, closing this for now, and we will reconsider when there is a lot more demand and as part of a possible bigger refactor.
