### ISSUE TITLE
Organising Post Snippets

### ISSUE THREAD

**Issue by artstorm** [davdebcom/post-snippets#38]
Is there a way to organise the post snippets, say alphabetically or even better into groups?
Don't mind digging a round in some code if need be!
https://wordpress.org/plugins/post-snippets/

Post Link: https://wordpress.org/support/topic/organising-post-snippets?replies=1#post-6547369

**Comment by davdebcom** [comment]
Expand/collapse will be added in the next free version update (3.0), Groups can only implemented after migration to new data format (3.2?).
