### ISSUE TITLE
When "Shortcode" is on variables arn't resolved

### ISSUE THREAD

**Issue by SciLor** [davdebcom/post-snippets#66]
With Post Snippets 2.5.3 and the latest WP the variables are not resolved if shortcode is enabled. If I disable that, it works fine.

**Comment by davdebcom** [comment]
@sultann Can you check if this still happens after the refactor for PHP 7.2?

**Comment by davdebcom** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 66: When "Shortcode" is on variables aren't resolved](https://trello.com/c/H88C2QL1/22-issue-66-when-shortcode-is-on-variables-arent-resolved)

**Comment by sultann** [comment]
This is working fine on the version 3.0.2

**Comment by davdebcom** [comment]
@SciLor Please reopen if you are still experiencing this with 3.0.2.
