### ISSUE TITLE
Improper HTML escaping of snippet titles

### ISSUE THREAD

**Issue by markstos** [davdebcom/post-snippets#67]
To reproduce the issue, try using a snippet title of:

     Hello '/><strong>XSS</strong>

You'll see that instead of being maintained as the title when displayed, only "Hello" is visible in the title, and  XSS appears in bold nearby.   This is a problem is your snippet is named "Plug Bill's Book".

Once the snippet is displayed and saved again, the title is changed.

I a simple test for XSS to see if I could get JavaScript to execute with a <script> tag, but I could not. 

I also only tested the title field for escaping problems. All the other fields should be checked as well.

**Comment by davdebcom** [comment]
@sultann Can you review and in when confirmed fix this?

**Comment by davdebcom** [comment]
Should be fixed by:
https://github.com/davdebcom/post-snippets/issues/79
https://github.com/davdebcom/post-snippets/issues/83
