### ISSUE TITLE
Filtering feature

### ISSUE THREAD

**Issue by walmaz** [davdebcom/post-snippets#74]
It would be great if each single snippet has an option to assign it to a specific post type only (like page or custom post type). I think such an enhancement might be a nice addition to this awesome plugin.

**Comment by davdebcom** [comment]
Thanks for the suggestion?

Could you explain it a bit more? 
Does your suggestion mean that the snippet wouldn't be shown in the other content even if the shortcode is used? Or that the entire snippet shouldn't be shown in the selection (pop-up)?

**Comment by walmaz** [comment]
I mean the entire snippet shouldn't be shown in the selection (pop-up). This is more about UI - I guess shortcodes might work everywhere.

**Comment by davdebcom** [comment]
Thanks, I understand the request and have noted it for consideration!
