### ISSUE TITLE
Need responsive UI

### ISSUE THREAD

**Issue by psycholyzern** [davdebcom/post-snippets#75]
![](https://i.imgur.com/QI1KkGg.png)

**Comment by davdebcom** [comment]
Hi @psycholyzern 

There will be a new UI in the big update (version 3), I expect that in Q1 2018. I'm not sure that will be responsive, but I'll keep your request in mind. Of course, feel free to make the existing UI responsive and add that code here as a pull request, I will definitely consider it!

Regards
David
