### ISSUE TITLE
Changes to how php is handled in snippets?

### ISSUE THREAD

**Issue by gerfoley** [davdebcom/post-snippets#88]
Has there been changes made to how php is handled in snippets in latest versions?

Php and escaped html that I had in use has now broken with the latest version.

**Comment by davdebcom** [comment]
I find backwards compatibility very important, so if something has broken with recent updates, I want to fix it. 

First of all, are you running 3.0.3 or higher? We reverted some changes to how slashes are parsed in that version. Using that issue might fix your issue.
https://wordpress.org/plugins/post-snippets/#developers

If you are, could you email me the content of your snippet on david AT davdeb DOT com so I can use that for testing. 

Closing this issue, I prefer to handle this (as we are talking about specific code on your site) via email.
